#ifndef BUTTONS_DEFINITIONS_H
#define BUTTONS_DEFINITIONS_H

#define BUTTON_COUNT (1)

#define BTN_DIO (14)
#define BTN_MASK (1 << BTN_DIO)
#define BTN_CTRL_MASK (BTN_MASK)

#endif /* BUTTONS_DEFINITIONS_H */
