#ifndef LEDS_DEFINITIONS_H
#define LEDS_DEFINITIONS_H

#define LED_LEFT_DIO (10)
#define LED_LEFT_MASK (1UL << LED_LEFT_DIO)
#define LED_RIGHT_DIO (11)
#define LED_RIGHT_MASK (1UL << LED_RIGHT_DIO)
#define LEDS_CTRL_MASK (LED_LEFT_MASK | LED_RIGHT_MASK)

#endif /* LEDS_DEFINITIONS_H */
