#ifndef APP_COMMON_H
#define APP_COMMON_H

#include "zps_gen.h"

#ifdef TARGET_WXKG07LM
#define BASIC_ENDPOINT WXKG07LM_BASIC_ENDPOINT
#define ZDO_ENDPOINT WXKG07LM_ZDO_ENDPOINT
#else
#define BASIC_ENDPOINT WXKG06LM_BASIC_ENDPOINT
#define ZDO_ENDPOINT WXKG06LM_ZDO_ENDPOINT
#endif

#endif /* APP_COMMON_H */
