#ifndef APP_COMMON_H
#define APP_COMMON_H

#include "zps_gen.h"
#include "app_led.h"

#ifdef TARGET_WXKG07LM

    #define BASIC_ENDPOINT WXKG07LM_BASIC_ENDPOINT
    #define ZDO_ENDPOINT WXKG07LM_ZDO_ENDPOINT

    #define APP_BTN1_ENDPOINT WXKG07LM_LEFTBUTTON_ENDPOINT
    #define APP_BTN1_BLINK_MODE BLINK_LED1
    #define APP_BTN2_ENDPOINT WXKG07LM_RIGHTBUTTON_ENDPOINT
    #define APP_BTN2_BLINK_MODE BLINK_LED2

    #define APP_BTN1_DIO (12) // left button DIO
    #define APP_BTN1_MASK (1 << APP_BTN1_DIO)
    #define APP_BTN2_DIO (16) // right button DIO
    #define APP_BTN2_MASK (1 << APP_BTN2_DIO)
    #define APP_BTN_CTRL_MASK (APP_BTN1_MASK | APP_BTN2_MASK)

    #define APP_BTN_RESET_MASK APP_BTN_CTRL_MASK
    #define APP_RESET_DEVICE_BLINK_MODE BLINK_BOTH
#elif defined(TARGET_WXKG06LM)
    #define BASIC_ENDPOINT WXKG06LM_BASIC_ENDPOINT
    #define ZDO_ENDPOINT WXKG06LM_ZDO_ENDPOINT

    #define APP_BTN1_ENDPOINT WXKG06LM_BUTTON_ENDPOINT
    #define APP_BTN1_BLINK_MODE BLINK_BOTH
    #define APP_BTN1_DIO (14) // button DIO
    #define APP_BTN_CTRL_MASK (1 << APP_BTN1_DIO)

    #define APP_BTN_RESET_MASK APP_BTN_CTRL_MASK
    #define APP_RESET_DEVICE_BLINK_MODE BLINK_BOTH

#elif defined(TARGET_WXKG11LM)

    #define BASIC_ENDPOINT WXKG11LM_BASIC_ENDPOINT
    #define ZDO_ENDPOINT WXKG11LM_ZDO_ENDPOINT

    #define APP_BTN1_ENDPOINT WXKG11LM_BUTTON_ENDPOINT
    #define APP_BTN1_BLINK_MODE BLINK_NONE
    #define APP_BTN1_DIO (16) // main button DIO
    #define APP_BTN1_MASK (1 << APP_BTN1_DIO)
    #define APP_BTN2_DIO (0) // commissioning button DIO
    #define APP_BTN2_MASK (1 << APP_BTN2_DIO)
    #define APP_BTN_CTRL_MASK (APP_BTN1_MASK | APP_BTN2_MASK)

    #define APP_BTN_RESET_MASK APP_BTN2_MASK
    #define APP_RESET_DEVICE_BLINK_MODE BLINK_LED1

#else
    #error "Unknown target device"
#endif

#endif /* APP_COMMON_H */
